CREATE EXTERNAL TABLE IF NOT EXISTS demogra(
  sex STRING,
  age STRING,
  area STRING,
  have_car STRING,
  have_cam STRING,
  have_pc STRING
)
PARTITIONED BY (job STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
